In [6]:
import sqlite3
import pandas as pd

# Load CSV
df = pd.read_csv(
    '/home/dell/Downloads/carbon emission impact analysis/data/processed/final_dataset.csv'
)

# Create SQLite database
conn = sqlite3.connect(
    '/home/dell/Downloads/carbon emission impact analysis/data/processed/carbon.db'
)

# Store dataframe as SQL table
df.to_sql(
    'carbon_data',
    conn,
    if_exists='replace',
    index=False
)

print("Data loaded into SQLite successfully.")

Data loaded into SQLite successfully.

In [14]:
# Top 5 Sustainable Countries

query = """
SELECT country,
       AVG(renewable_energy) AS renewable,
       AVG(co2_per_capita) AS co2
FROM carbon_data
GROUP BY country
HAVING renewable > 50
ORDER BY co2 ASC
LIMIT 5;
"""

sustainable_countries = pd.read_sql(query, conn)

sustainable_countries

                    country  renewable       co2
0                   Burundi  92.015152  0.029977
1  Central African Republic  91.933333  0.054790
2                  Ethiopia  93.918750  0.055171
3                    Rwanda  86.300000  0.057841
4                      Chad  81.554545  0.063548

In [15]:
# Countries With Highest Energy Consumption

query = """
SELECT country,
       AVG(energy_consumption) AS avg_energy
FROM carbon_data
GROUP BY country
ORDER BY avg_energy DESC
LIMIT 10;
"""

high_energy = pd.read_sql(query, conn)

high_energy

                country     avg_energy
0                 Qatar  185441.816900
1               Bahrain  148250.521932
2  United Arab Emirates  124130.425797
3               Iceland  108331.059867
4                Canada  106041.423283
5                Norway  100213.050983
6             Singapore   98865.235533
7                Kuwait   97505.322450
8            Luxembourg   97239.352550
9                Brunei   96665.055750

In [16]:
# Countries With Highest Energy Consumption

query = """
SELECT country,
       AVG(energy_consumption) AS avg_energy
FROM carbon_data
GROUP BY country
ORDER BY avg_energy DESC
LIMIT 10;
"""

high_energy = pd.read_sql(query, conn)

high_energy

                country     avg_energy
0                 Qatar  185441.816900
1               Bahrain  148250.521932
2  United Arab Emirates  124130.425797
3               Iceland  108331.059867
4                Canada  106041.423283
5                Norway  100213.050983
6             Singapore   98865.235533
7                Kuwait   97505.322450
8            Luxembourg   97239.352550
9                Brunei   96665.055750

In [17]:
# Year With Highest Average CO₂

query = """
SELECT year,
       AVG(co2_per_capita) AS avg_co2
FROM carbon_data
GROUP BY year
ORDER BY avg_co2 DESC
LIMIT 1;
"""

highest_co2_year = pd.read_sql(query, conn)

highest_co2_year

   year   avg_co2
0  1954  6.998409

In [18]:
# Average GDP By Decade

query = """
SELECT (year/10)*10 AS decade,
       AVG(gdp) AS avg_gdp
FROM carbon_data
GROUP BY decade
ORDER BY decade;
"""

gdp_decade = pd.read_sql(query, conn)

gdp_decade

    decade       avg_gdp
0     1750           NaN
1     1760           NaN
2     1770           NaN
3     1780           NaN
4     1790           NaN
5     1800           NaN
6     1810           NaN
7     1820           NaN
8     1830           NaN
9     1840           NaN
10    1850           NaN
11    1860           NaN
12    1870           NaN
13    1880           NaN
14    1890           NaN
15    1900           NaN
16    1910           NaN
17    1920           NaN
18    1930           NaN
19    1940           NaN
20    1950           NaN
21    1960  1.762238e+10
22    1970  4.246879e+10
23    1980  9.403749e+10
24    1990  1.601856e+11
25    2000  2.506196e+11
26    2010  4.130584e+11
27    2020  5.443073e+11

In [19]:
# Countries With Low Emissions But High GDP

query = """
SELECT country,
       AVG(gdp) AS avg_gdp,
       AVG(co2_per_capita) AS avg_co2
FROM carbon_data
GROUP BY country
HAVING avg_gdp > 100000000000
   AND avg_co2 < 5;
"""

low_emission_rich = pd.read_sql(query, conn)

low_emission_rich

        country       avg_gdp   avg_co2
0     Argentina  2.262171e+11  1.864305
1       Austria  2.014848e+11  3.853148
2        Brazil  7.826144e+11  0.732299
3         China  3.590132e+12  1.925319
4      Colombia  1.210965e+11  0.717452
5       Denmark  1.657718e+11  4.919385
6       Finland  1.276684e+11  4.079250
7        France  1.357085e+12  3.732687
8        Greece  1.220412e+11  2.913965
9         India  8.344544e+11  0.414751
10    Indonesia  3.711335e+11  0.636853
11        Italy  1.081094e+12  2.859904
12        Japan  2.955884e+12  3.866396
13     Malaysia  1.190766e+11  2.227339
14       Mexico  5.596014e+11  1.869898
15      Nigeria  1.744432e+11  0.368033
16       Norway  1.910586e+11  3.032907
17     Pakistan  1.082759e+11  0.488393
18  Philippines  1.163344e+11  0.470310
19       Poland  3.807119e+11  3.955653
20     Portugal  1.104319e+11  1.854255
21      Romania  1.330010e+11  2.611798
22        Spain  6.430102e+11  2.107282
23       Sweden  2.642585e+11  3.515086
24  Switzerland  3.156572e+11  3.114731
25     Thailand  1.648809e+11  1.440456
26      Ukraine  1.045235e+11  3.901725

In [20]:
# Renewable Energy Leaders

query = """
SELECT country,
       MAX(renewable_energy) AS renewable_peak
FROM carbon_data
GROUP BY country
ORDER BY renewable_peak DESC
LIMIT 10;
"""

renewable_leaders = pd.read_sql(query, conn)

renewable_leaders

                    country  renewable_peak
0                  Ethiopia            97.5
1                    Uganda            97.3
2                     Haiti            96.7
3                   Burundi            96.0
4                    Bhutan            95.9
5                  Tanzania            95.2
6                     Nepal            95.1
7  Central African Republic            95.1
8              Sierra Leone            95.0
9                     Benin            95.0